# @package _global_
# Copyright (C) 2026 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

feature_extractor_cfg:
  _target_: nassl.feature_extraction_model.FE_EAT
  model_id: "worstchan/EAT-base_epoch30_pretrain"
