# Copyright (C) 2026 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_target_: nassl.plmodel.NoiseAwarePLModel
model_cfg:
  _target_: nassl.model.NABEATs
  model_id: "BEATs_iter3"
  trainable_base: false
  eval_base: false
  fusion_layer_cfg:
    _target_: nassl.module.fusion.PreNormFiLMFFNBlock
    init_identity: true
loss_cfg:
  _target_: nassl.loss.MSELoss
optim_cfg:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
lrscheduler_cfg: null
teacher_model_cfg:
  _target_: nassl.feature_extraction_model.FE_BEATs
  model_id: ${plmodel.model_cfg.model_id}
